query ProblemEditDetailGQL($slug: String!) {
	problem(slug: $slug) {
		pk
		title
		content
		standardInput
		standardOutput
		constraints
		sources
		note
		limitation{
			timeLimit
			memoryLimit
			outputLimit
			cpuLimit
		}
        disabled
        private
		samples {
			sampleList{
				inputContent
				outputContent
			}
		}
	}
}
